### ISSUE TITLE
Please help.. Error during install of payload

### ISSUE THREAD

**Issue by BrianGilbert** [reswitched/fusee-launcher#23]
via a 2017 rMBP

Python 3 installed via homebrew, pyusb and libusb installed using: pip3 install
```
$ sudo python3 fusee-launcher.py fusee.bin
Alias tip: _ python3 fusee-launcher.py fusee.bin
Traceback (most recent call last):
  File "fusee-launcher.py", line 594, in <module>
    pid=arguments.pid, os_override=arguments.platform, override_checks=arguments.skip_checks)
  File "fusee-launcher.py", line 466, in __init__
    self.dev = self._find_device(vid, pid)
  File "fusee-launcher.py", line 496, in _find_device
    return self.backend.find_device(vid, pid)
  File "fusee-launcher.py", line 135, in find_device
    self.dev = usb.core.find(idVendor=vid, idProduct=pid)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by BrianGilbert** [comment]
Resolved by insyallin libusb via homebrew:

```
brew install libusb

**Comment by baptisteArnaud** [comment]
> Resolved by installing libusb via homebrew:
> 
> ```
> brew install libusb
> ```

I have the same error and it didn't solve the problem
